if (isClass(configFile >> "CfgPatches" >> "rhsgref_main")) then {MOD_hasRHSGREF = true;}else {MOD_hasRHSGREF = false;};
if (isClass(configFile >> "CfgPatches" >> "rhsusf_main")) then {MOD_hasRHSUS = true;}  else {MOD_hasRHSUS = false;};
if (isClass(configFile >> "CfgPatches" >> "rhs_main")) then 	{MOD_hasRHS = true;}else {MOD_hasRHS = false;};
if (isClass(configFile >> "CfgPatches" >> "rhssaf_main")) then {MOD_hasRHSSAF = true;}else {MOD_hasRHSSAF = false;};
if (isClass(configFile >> "CfgPatches" >> "SMA_Weapons")) then {MOD_hasSMA = true;}else {MOD_hasSMA = false;};
if (isClass(configfile >> "CfgPatches" >> "hlcweapons_acr")) then {MOD_hasNIA_ACR = true;}else {MOD_hasNIA_ACR = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_aks")) then {MOD_hasNIA_AK = true;}else {MOD_hasNIA_AK = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_ar15")) then {MOD_hasNIA_AR = true;}else {MOD_hasNIA_AR = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_M16A2")) then {MOD_hasNIA_M16 = true;}else {MOD_hasNIA_M16 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_AUG")) then {MOD_hasNIA_AUG = true;}else {MOD_hasNIA_AUG = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_falpocalypse")) then {MOD_hasNIA_FAL = true;}else {MOD_hasNIA_FAL = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_FHAWCovert")) then {MOD_hasNIA_AW = true;}else {MOD_hasNIA_AW = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_g3")) then {MOD_hasNIA_G3 = true;}else {MOD_hasNIA_G3 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_g36")) then {MOD_hasNIA_g36 = true;}else {MOD_hasNIA_g36 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_M134")) then {MOD_hasNIA_M134 = true;}else {MOD_hasNIA_M134 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_M14")) then {MOD_hasNIA_M14 = true;}else {MOD_hasNIA_M14 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_m60e4")) then {MOD_hasNIA_M60 = true;}else {MOD_hasNIA_M60 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_MG3s")) then {MOD_hasNIA_MG3 = true;}else {MOD_hasNIA_MG3 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_mp5")) then {MOD_hasNIA_MP5 = true;}else {MOD_hasNIA_MP5 = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_SAW")) then {MOD_hasNIA_SAW = true;}else {MOD_hasNIA_SAW = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_SG550")) then {MOD_hasNIA_SG = true;}else {MOD_hasNIA_SG = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_Springfield1903")) then {MOD_hasNIA_SF = true;}else {MOD_hasNIA_SF = false;};
if (isClass(configFile >> "CfgPatches" >> "hlcweapons_stgw57")) then {MOD_hasNIA_STG = true;}else {MOD_hasNIA_STG = false;};
if (isClass(configFile >> "CfgPatches" >> "niarms_416")) then {MOD_hasNIA_416 = true;}else {MOD_hasNIA_416 = false;};
if (isClass(configFile >> "CfgPatches" >> "niaweapons_226")) then {MOD_hasNIA_226 = true;}else {MOD_hasNIA_226 = false;};
if (isClass(configFile >> "CfgPatches" >> "niaweapons_C96")) then {MOD_hasNIA_C96 = true;}else {MOD_hasNIA_C96 = false;};
if (isClass(configfile >> "CfgPatches" >> "ace_main")) then {MOD_hasACE = true;}else {MOD_hasACE = false;};
if (isClass(configfile >> "CfgPatches" >> "ace_medical")) then {MOD_hasACEMedical = true;}else {MOD_hasACEMedical = false;};
if (isClass(configfile >> "CfgPatches" >> "task_force_radio")) then {MOD_hasTF = true;}else {MOD_hasTF = false;};
if (isClass(configfile >> "CfgPatches" >> "TRYK_Uniform")) then {MOD_hasTRYK = true;}else {MOD_hasTRYK = false;};
if (isClass(configfile >> "CfgPatches" >> "TAC_VESTS")) then {MOD_hasTAC = true;}else {MOD_hasTAC = false;};
if (isClass(configfile >> "CfgPatches" >> "KA_Weapon_Functions")) then {MOD_hasKA = true;}else {MOD_hasKA = false;};
publicVariable 'MOD_hasRHSGREF';
publicVariable 'MOD_hasRHSUS';
publicVariable 'MOD_hasRHS';
publicVariable 'MOD_hasRHSSAF';
publicVariable 'MOD_hasSMA';
publicVariable 'MOD_hasACE';
publicVariable 'MOD_hasACEMedical';
publicVariable 'MOD_hasTF';
publicVariable 'MOD_hasTRYK';
publicVariable 'MOD_hasTAC';
publicVariable "MOD_hasNIA_ACR";
publicVariable "MOD_hasNIA_AK";
publicVariable "MOD_hasNIA_AR";
publicVariable "MOD_hasNIA_M16";
publicVariable "MOD_hasNIA_AUG";
publicVariable "MOD_hasNIA_FAL";
publicVariable "MOD_hasNIA_AW";
publicVariable "MOD_hasNIA_G3";
publicVariable "MOD_hasNIA_g36";
publicVariable "MOD_hasNIA_M134";
publicVariable "MOD_hasNIA_M14";
publicVariable "MOD_hasNIA_M60";
publicVariable "MOD_hasNIA_MG3";
publicVariable "MOD_hasNIA_MP5";
publicVariable "MOD_hasNIA_SAW";
publicVariable "MOD_hasNIA_SG";
publicVariable "MOD_hasNIA_416";
publicVariable "MOD_hasNIA_226";
publicVariable "MOD_hasNIA_C96";
publicVariable "MOD_hasKA";

gp_fnc_lootAddAction =
{
	_this addAction ["<img image='HG\UI\Icons\money.paa' size='1.5'/>"+(localize 'str_system_loot'),'scripts\loot.sqf',nil,10000,true,false,'','true',5];
};
